services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  bot_dev:
    build:
      context: .
      dockerfile: docker/dev.Dockerfile
    volumes:
      - ./src:/app/src
    environment:
      DB_HOST: db
      BOT_ADMIN_CHAT_ID: ${BOT_ADMIN_CHAT_ID}
      BOT_TOKEN: ${BOT_TOKEN_DEV}
      DB_URL: postgres://${DB_USER}:${DB_PASSWORD}@db:5432/${DB_NAME}
    depends_on:
      - db

volumes:
  pg_data:
